-- COMPLETE 380+ EXERCISE DATABASE
-- Run this ONCE in Supabase SQL Editor to get all exercises
-- Uses ON CONFLICT to automatically skip duplicates

INSERT INTO exercises (name, category, difficulty, equipment, is_default, is_custom, image_url) VALUES
-- CHEST (All 46 exercises)
('Bench Press (Barbell)', 'Chest', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Bench Press (Dumbbell)', 'Chest', 'Intermediate', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Bench Press (Cable)', 'Chest', 'Intermediate', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Bench Press (Smith Machine)', 'Chest', 'Intermediate', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Bench Press - Close Grip (Barbell)', 'Chest', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Bench Press - Wide Grip (Barbell)', 'Chest', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Incline Bench Press (Barbell)', 'Chest', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Incline Bench Press (Dumbbell)', 'Chest', 'Intermediate', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Incline Bench Press (Smith Machine)', 'Chest', 'Intermediate', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Decline Bench Press (Barbell)', 'Chest', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Decline Bench Press (Dumbbell)', 'Chest', 'Intermediate', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Decline Bench Press (Machine)', 'Chest', 'Intermediate', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Decline Bench Press (Smith Machine)', 'Chest', 'Intermediate', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Cable Fly Crossovers', 'Chest', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Low Cable Fly Crossovers', 'Chest', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Chest Fly (Band)', 'Chest', 'Beginner', 'Band', true, false, 'Exercises/default_exercise.gif'),
('Chest Fly (Dumbbell)', 'Chest', 'Beginner', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Chest Fly (Machine)', 'Chest', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Chest Fly (Suspension)', 'Chest', 'Intermediate', 'Suspension', true, false, 'Exercises/default_exercise.gif'),
('Incline Chest Fly (Dumbbell)', 'Chest', 'Beginner', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Decline Chest Fly (Dumbbell)', 'Chest', 'Beginner', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Chest Press (Band)', 'Chest', 'Beginner', 'Band', true, false, 'Exercises/default_exercise.gif'),
('Chest Press (Machine)', 'Chest', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Incline Chest Press (Machine)', 'Chest', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Iso-Lateral Chest Press (Machine)', 'Chest', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Seated Chest Flys (Cable)', 'Chest', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Chest Dip', 'Chest', 'Intermediate', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Chest Dip (Assisted)', 'Chest', 'Beginner', 'Assisted', true, false, 'Exercises/default_exercise.gif'),
('Ring Dips', 'Chest', 'Advanced', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Push Up', 'Chest', 'Beginner', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Push Up (Weighted)', 'Chest', 'Intermediate', 'Weighted', true, false, 'Exercises/default_exercise.gif'),
('Push Up - Close Grip', 'Chest', 'Intermediate', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Diamond Push Up', 'Chest', 'Intermediate', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Decline Push Up', 'Chest', 'Intermediate', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Incline Push Ups', 'Chest', 'Beginner', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Kneeling Push Up', 'Chest', 'Beginner', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Clap Push Ups', 'Chest', 'Advanced', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('One Arm Push Up', 'Chest', 'Advanced', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Plank Pushup', 'Chest', 'Intermediate', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Around The World', 'Chest', 'Beginner', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Butterfly (Pec Deck)', 'Chest', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Floor Press (Dumbbell)', 'Chest', 'Intermediate', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Hex Press (Dumbbell)', 'Chest', 'Intermediate', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Plate Press', 'Chest', 'Beginner', 'Plate', true, false, 'Exercises/default_exercise.gif'),
('Plate Squeeze (Svend Press)', 'Chest', 'Beginner', 'Plate', true, false, 'Exercises/default_exercise.gif'),
('Chest Supported Incline Row (Dumbbell)', 'Back', 'Beginner', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),

-- BACK (All 58 exercises)
('Deadlift (Barbell)', 'Back', 'Advanced', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Deadlift (Band)', 'Back', 'Intermediate', 'Band', true, false, 'Exercises/default_exercise.gif'),
('Deadlift (Dumbbell)', 'Back', 'Intermediate', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Deadlift (Smith Machine)', 'Back', 'Intermediate', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Deadlift (Trap bar)', 'Back', 'Advanced', 'Trap Bar', true, false, 'Exercises/default_exercise.gif'),
('Sumo Deadlift', 'Back', 'Advanced', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Romanian Deadlift (Barbell)', 'Back', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Romanian Deadlift (Dumbbell)', 'Back', 'Intermediate', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Straight Leg Deadlift', 'Back', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Rack Pull', 'Back', 'Advanced', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Deadlift High Pull', 'Back', 'Advanced', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Bent Over Row (Barbell)', 'Back', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Bent Over Row (Band)', 'Back', 'Beginner', 'Band', true, false, 'Exercises/default_exercise.gif'),
('Bent Over Row (Dumbbell)', 'Back', 'Intermediate', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Dumbbell Row', 'Back', 'Beginner', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('T Bar Row', 'Back', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Landmine Row', 'Back', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Gorilla Row (Kettlebell)', 'Back', 'Intermediate', 'Kettlebell', true, false, 'Exercises/default_exercise.gif'),
('Renegade Row (Dumbbell)', 'Back', 'Advanced', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Seated Cable Row - V Grip (Cable)', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Seated Cable Row - Bar Grip', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Seated Cable Row - Bar Wide Grip', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Seated Row (Machine)', 'Back', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Iso-Lateral Row (Machine)', 'Back', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Iso-Lateral High Row (Machine)', 'Back', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Iso-Lateral Low Row', 'Back', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Low Row (Suspension)', 'Back', 'Beginner', 'Suspension', true, false, 'Exercises/default_exercise.gif'),
('Pull Up', 'Back', 'Intermediate', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Pull Up (Assisted)', 'Back', 'Beginner', 'Assisted', true, false, 'Exercises/default_exercise.gif'),
('Pull Up (Band)', 'Back', 'Beginner', 'Band', true, false, 'Exercises/default_exercise.gif'),
('Pull Up (Weighted)', 'Back', 'Advanced', 'Weighted', true, false, 'Exercises/default_exercise.gif'),
('Wide Pull Up', 'Back', 'Intermediate', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Chin Up', 'Back', 'Intermediate', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Chin Up (Assisted)', 'Back', 'Beginner', 'Assisted', true, false, 'Exercises/default_exercise.gif'),
('Chin Up (Weighted)', 'Back', 'Advanced', 'Weighted', true, false, 'Exercises/default_exercise.gif'),
('Negative Pull Up', 'Back', 'Beginner', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Sternum Pull up (Gironda)', 'Back', 'Advanced', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Scapular Pull Ups', 'Back', 'Beginner', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Lat Pulldown (Cable)', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Lat Pulldown (Band)', 'Back', 'Beginner', 'Band', true, false, 'Exercises/default_exercise.gif'),
('Lat Pulldown (Machine)', 'Back', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Lat Pulldown - Close Grip (Cable)', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Reverse Grip Lat Pulldown (Cable)', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Single Arm Lat Pulldown', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Kneeling Pulldown (band)', 'Back', 'Beginner', 'Band', true, false, 'Exercises/default_exercise.gif'),
('Straight Arm Lat Pulldown (Cable)', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Rope Straight Arm Pulldown', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Pullover (Dumbbell)', 'Back', 'Intermediate', 'Dumbbell', true, false, 'Exercises/default_exercise.gif'),
('Pullover (Machine)', 'Back', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Inverted Row', 'Back', 'Beginner', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Face Pull', 'Back', 'Beginner', 'Cable', true, false, 'Exercises/default_exercise.gif'),
('Dead Hang', 'Back', 'Beginner', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Back Extension (Hyperextension)', 'Back', 'Beginner', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Back Extension (Machine)', 'Back', 'Beginner', 'Machine', true, false, 'Exercises/default_exercise.gif'),
('Back Extension (Weighted Hyperextension)', 'Back', 'Intermediate', 'Weighted', true, false, 'Exercises/default_exercise.gif'),
('Reverse Hyperextension', 'Back', 'Intermediate', 'Bodyweight', true, false, 'Exercises/default_exercise.gif'),
('Good Morning (Barbell)', 'Back', 'Intermediate', 'Barbell', true, false, 'Exercises/default_exercise.gif'),
('Superman', 'Back', 'Beginner', 'Bodyweight', true, false, 'Exercises/default_exercise.gif')

ON CONFLICT (name) DO NOTHING;

-- Continue in next message...
